clan:
  tag: "%232lp8rlqp"
  url:  https://api.clashofclans.com/v1
  api_token: ${ENV_API_TOKEN}

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #datasource:
  #  driver-class-name: org.h2.Driver
  #  url: jdbc:h2:~/test
  #  username: sa
  #  password:
  datasource:
    url: jdbc:postgresql://database-1.chs25sn7aqkx.ap-northeast-1.rds.amazonaws.com:5432/coc
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}
  jpa:
    generate-ddl: true
